#!/bin/bash
make install
nsd unsafe-reset-all
rm -rf ~/.ns*
nsd init moniker --chain-id namechain
nscli keys add jack
nscli keys add alice
nsd add-genesis-account $(nscli keys show jack -a) 1000nametoken,1000xyztoken,100000000stake
nsd add-genesis-account $(nscli keys show alice -a) 1000nametoken,1000xyztoken,100000000stake
nscli config chain-id namechain
nscli config output json
nscli config indent true
nscli config trust-node true
nsd gentx --name jack
nsd collect-gentxs
nsd validate-genesis
nsd start